DROP TABLE IF EXISTS linesinbasket;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS linesinorder;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS basket;
DROP TABLE IF EXISTS statusoforder;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS categories;
