-- vef2-2022-hop1 --

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- menu tables --

CREATE TABLE IF NOT EXISTS categories (
  id SERIAL PRIMARY KEY UNIQUE,
  name VARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS products (
  id SERIAL PRIMARY KEY UNIQUE,
  name VARCHAR(256) NOT NULL UNIQUE,
  price INTEGER NOT NULL,
  description TEXT NOT NULL,
  image VARCHAR(256) NOT NULL,
  categoryId INTEGER NOT NULL,
  created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_products_categories FOREIGN KEY (categoryId) REFERENCES categories (id) ON DELETE CASCADE
);

-- basket tables --

CREATE TABLE IF NOT EXISTS basket (
  id uuid PRIMARY KEY UNIQUE DEFAULT uuid_generate_v4(),
  created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS linesinbasket (
  productId INTEGER NOT NULL,
  basketId uuid NOT NULL,
  nrofproducts INTEGER NOT NULL,
  CONSTRAINT nrofprodnotnull check (nrofproducts > 0),
  CONSTRAINT FK_prod_product FOREIGN KEY (productId) REFERENCES products (id) ON DELETE CASCADE,
  CONSTRAINT FK_bask_basket FOREIGN KEY (basketId) REFERENCES basket (id) ON DELETE CASCADE
);

-- order tables --

CREATE TABLE IF NOT EXISTS orders (
  id uuid PRIMARY KEY UNIQUE,
  created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS linesinorder (
  productId INTEGER NOT NULL,
  basketId uuid NOT NULL,
  nrofproducts INTEGER NOT NULL,
  CONSTRAINT nrofprodnotnull check (nrofproducts > 0),
  CONSTRAINT FK_prod_product FOREIGN KEY (productId) REFERENCES products (id) ON DELETE CASCADE,
  CONSTRAINT FK_bask_basket FOREIGN KEY (basketId) REFERENCES basket (id) ON DELETE CASCADE
);

DROP TYPE IF EXISTS stateoforder CASCADE;
CREATE TYPE stateoforder AS ENUM ('NEW', 'PREPARE','COOKING', 'READY', 'FINISHED');

CREATE TABLE IF NOT EXISTS statusoforders (
  id uuid SERIAL PRIMARY KEY,
  status stateoforder,
  created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
  CONSTRAIN FK_status FOREIGN KEY (id) REFERENCES orders (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(256) NOT NULL,
  username VARCHAR(256) NOT NULL UNIQUE,
  email VARCHAR(256) NOT NULL UNIQUE,
  password VARCHAR(256) NOT NULL,
  admin BOOLEAN DEFAULT false,
  created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp,
  updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp
);




